### ISSUE TITLE
Initial connection failover to subsequent hosts

### ISSUE THREAD

**Issue by LunaTakaishi** [DirectoryTree/LdapRecord#236]
**Environment (please complete the following information):**
 - LDAP Server Type: ActiveDirectory
 - PHP: v7.4.12
 - Laravel: v6
 - directorytree/ldaprecord   v2.0.3
 - directorytree/ldaprecord-laravel   v2.0.1

I have multiple ldap hosts servers.
The hosts IP address is passed as an Array. If the first connection fails, I would like you to start the second validation.

However, it does not work as expected.
Even if hosts is passed as an Array, an error will be returned if the first validation fails.

i tried it.

 - .env
```
LDAP_HOST=0.0.0.1,0.0.0.2
```

 - config/ldap.php
```
'connections' => [
        'default' => [
            'hosts' => array_map('trim', explode(',', env('LDAP_HOST', '127.0.0.1'))), // I modified it here
```

However, in reality, the first array is used for processing.
So I edited \directorytree\ldaprecord\src\Connection.php

```
public function __construct($config = [], Ldap $ldap = null)
    {
        $this->configuration = new DomainConfiguration($config);

        $this->hosts = $this->configuration->get('hosts');

        //$this->host = reset($this->hosts); 
        $this->host = $this->hosts; // I modified it here

        $this->setLdapConnection($ldap ?? new Ldap());
    }
```

Please let me know if there is another good way.
Thanks.

**Comment by stevebauman** [comment]
Hi @LunaTakaishi, this is actually intended -- as only fallback will only occur when an operation **other than** an `ldap_bind` request will be re-tried (such as a query operation, modification operation, creation operation, etc.). But I can see now that binds should also fallback to other hosts.

Thanks for bringing this up! Right now -- there's no way around this unless you've modify the core, which we don't want you to have to do. Give me a couple days and I should have this implemented and released 👍

**Comment by LunaTakaishi** [comment]
Hi @stevebauman ,Thank you for your prompt reply.
I’m waiting a great fix.

**Comment by stevebauman** [comment]
Fixed! 🎉   I've just release [v2.0.4](https://github.com/DirectoryTree/LdapRecord/releases/tag/v2.0.4) which contains this patch.

Please run `composer update` to download the latest patch and automated connection failover will now occur during initial connection attempts.

Thanks so much for the bug report! ❤️ 

Let me know if you encounter any further issues! 👍

**Comment by LunaTakaishi** [comment]
Hi @stevebauman ,Thank you for fixing it! 
But I still have a problem. I've tried it on multiple hosts, but it doesn't work.😭
I think the cause is that I couldn't call `Connection.php retry()` from `Connection.php tryAgainIfCausedByLostConnection()`.
This throw seems to return an error.

\directorytree\ldaprecord\src\Connection.php Line371~
```
    protected function tryAgainIfCausedByLostConnection(LdapRecordException $e, Closure $operation)
    {
        // If the operation failed due to a lost or failed connection,
        // we'll attempt reconnecting and running the operation again
        // underneath the same host, and then move onto the next.
        if ($this->causedByLostConnection($e->getMessage())) {
            return $this->retry($operation);
        }

        throw $e;
    }
```

If something isn't clear, please let me know.

**Comment by stevebauman** [comment]
Hi @LunaTakaishi,

You shouldn't call the `retry` method manually -- it's done for your automatically. Are you sure you're on the new version? Can you open up your `composer.lock` file and see that the version of LdapRecord is `v2.0.4`?

Have you inserted at least one valid host in the array? I tested fail-over on my end and it works without issue. If no hosts can be contacted, then an exception will still be thrown.

**Comment by LunaTakaishi** [comment]
Hi @stevebauman,
I haven't called the retry method manually. Also, the version of `directorytree/ldaprecord` is `v2.0.4`.

composer.lock picture.
![image](https://user-images.githubusercontent.com/28255411/105267815-e64e0800-5bd4-11eb-91de-190fc51ad9d5.png)

The array containing hosts contains valid hosts. If you put in a valid host for the first time, it works fine. However, if you put in the first invalid host and the second valid host, you will get an error.

**Comment by stevebauman** [comment]
What error do you get? Can you post it with a stack trace?

**Comment by LunaTakaishi** [comment]
No error is printed in the stack trace."No error is printed in the stack trace." Is output on the screen.

**Comment by stevebauman** [comment]
That’s bizarre... Can you post how you’re utilizing LdapRecord in your application? Or does this occur when you’re trying to authenticate users?

**Comment by LunaTakaishi** [comment]
- .env 
```
LDAP_HOST=0.0.0.1,<REAL_HOST_IP>
```

 - config/ldap.php
```
'connections' => [
        'default' => [
            'hosts' => array_map('trim', explode(',', env('LDAP_HOST', '127.0.0.1'))), // I modified it here
```

And I added Log here. Other code has not been modified.
\directorytree\ldaprecord\src\Connection.php Line371~
```
protected function tryAgainIfCausedByLostConnection(LdapRecordException $e, Closure $operation)
    {
        // If the operation failed due to a lost or failed connection,
        // we'll attempt reconnecting and running the operation again
        // underneath the same host, and then move onto the next.
        if ($this->causedByLostConnection($e->getMessage())) {
            return $this->retry($operation);
        }
        \Log::info($e);  // I modified it here

        throw $e;
    }
```

Stack trace at this time
```
```
[2021-01-21 12:12:14] local.INFO: LDAP (ldap://0.0.0.1:389) - Operation: Binding - Username: @@@@@@@@\#######  
[2021-01-21 12:12:14] local.INFO: Illuminate\Validation\ValidationException: The given data was invalid. in /var/www/vendor/laravel/framework/src/Illuminate/Validation/ValidationException.php:71
Stack trace:
#0 /var/www/vendor/directorytree/ldaprecord-laravel/src/Auth/ListensForLdapBindFailure.php(118): Illuminate\Validation\ValidationException::withMessages(Array)
#1 /var/www/vendor/directorytree/ldaprecord-laravel/src/Auth/ListensForLdapBindFailure.php(91): App\Http\Controllers\Auth\LoginController->throwLoginValidationException('Can't contact L...')
#2 /var/www/vendor/directorytree/ldaprecord-laravel/src/Auth/ListensForLdapBindFailure.php(62): App\Http\Controllers\Auth\LoginController->handleLdapBindError('Can't contact L...')
#3 /var/www/vendor/directorytree/ldaprecord-laravel/src/Auth/ListensForLdapBindFailure.php(44): App\Http\Controllers\Auth\LoginController->ldapBindFailed('Can't contact L...', NULL)
#4 /var/www/vendor/directorytree/ldaprecord/src/Events/Dispatcher.php(269): App\Http\Controllers\Auth\LoginController->LdapRecord\Laravel\Auth\{closure}(Object(LdapRecord\Auth\Events\Failed))
#5 /var/www/vendor/directorytree/ldaprecord/src/Events/Dispatcher.php(112): LdapRecord\Events\Dispatcher->LdapRecord\Events\{closure}('LdapRecord\\Auth...', Array)
#6 /var/www/vendor/directorytree/ldaprecord/src/Events/Dispatcher.php(93): LdapRecord\Events\Dispatcher->dispatch('LdapRecord\\Auth...', Array, false)
#7 /var/www/vendor/directorytree/ldaprecord/src/Auth/Guard.php(202): LdapRecord\Events\Dispatcher->fire(Object(LdapRecord\Auth\Events\Failed))
#8 /var/www/vendor/directorytree/ldaprecord/src/Auth/Guard.php(118): LdapRecord\Auth\Guard->fireFailedEvent('@@@@@@@@\#######', 'password')
#9 /var/www/vendor/directorytree/ldaprecord/src/Auth/Guard.php(135): LdapRecord\Auth\Guard->bind('@@@@@@@@\#######', 'password')
#10 /var/www/vendor/directorytree/ldaprecord/src/Connection.php(203): LdapRecord\Auth\Guard->bindAsConfiguredUser()
#11 /var/www/vendor/directorytree/ldaprecord/src/Connection.php(311): LdapRecord\Connection->LdapRecord\{closure}(Object(LdapRecord\Ldap))
#12 /var/www/vendor/directorytree/ldaprecord/src/Connection.php(208): LdapRecord\Connection->runOperationCallback(Object(Closure))
#13 /var/www/vendor/directorytree/ldaprecord/src/Connection.php(265): LdapRecord\Connection->connect()
#14 /var/www/vendor/directorytree/ldaprecord/src/Query/Builder.php(528): LdapRecord\Connection->run(Object(Closure))
#15 /var/www/vendor/directorytree/ldaprecord/src/Query/Builder.php(397): LdapRecord\Query\Builder->run('(&(objectclass=...')
#16 /var/www/vendor/directorytree/ldaprecord/src/Query/Builder.php(498): LdapRecord\Query\Builder->LdapRecord\Query\{closure}()
#17 /var/www/vendor/directorytree/ldaprecord/src/Query/Builder.php(400): LdapRecord\Query\Builder->getCachedResponse('(&(objectclass=...', Object(Closure))
#18 /var/www/vendor/directorytree/ldaprecord/src/Query/Builder.php(223): LdapRecord\Query\Builder->query('(&(objectclass=...')
#19 /var/www/vendor/directorytree/ldaprecord/src/Query/Builder.php(245): LdapRecord\Query\Builder->LdapRecord\Query\{closure}()
#20 /var/www/vendor/directorytree/ldaprecord/src/Query/Builder.php(224): LdapRecord\Query\Builder->onceWithColumns(Array, Object(Closure))
#21 /var/www/vendor/directorytree/ldaprecord/src/Query/Builder.php(691): LdapRecord\Query\Builder->get(Array)
#22 /var/www/vendor/directorytree/ldaprecord-laravel/src/LdapUserRepository.php(100): LdapRecord\Query\Builder->first()
#23 /var/www/vendor/directorytree/ldaprecord-laravel/src/Auth/UserProvider.php(46): LdapRecord\Laravel\LdapUserRepository->findByCredentials(Array)
#24 [internal function]: LdapRecord\Laravel\Auth\UserProvider->LdapRecord\Laravel\Auth\{closure}(Array)
#25 /var/www/vendor/directorytree/ldaprecord-laravel/src/Auth/UserProvider.php(62): call_user_func(Object(Closure), Array)
#26 /var/www/vendor/directorytree/ldaprecord-laravel/src/Auth/DatabaseUserProvider.php(142): LdapRecord\Laravel\Auth\UserProvider->fetchLdapUserByCredentials(Array)
#27 /var/www/vendor/laravel/framework/src/Illuminate/Auth/SessionGuard.php(357): LdapRecord\Laravel\Auth\DatabaseUserProvider->retrieveByCredentials(Array)
#28 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Auth/AuthenticatesUsers.php(82): Illuminate\Auth\SessionGuard->attempt(Array, false)
#29 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Auth/AuthenticatesUsers.php(45): App\Http\Controllers\Auth\LoginController->attemptLogin(Object(Illuminate\Http\Request))
#30 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\Http\Controllers\Auth\LoginController->login(Object(Illuminate\Http\Request))
#31 /var/www/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('login', Array)
#32 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\Auth\LoginController), 'login')
#33 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\Routing\Route->runController()
#34 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\Routing\Route->run()
#35 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#36 /var/www/app/Http/Middleware/RedirectIfAuthenticated.php(24): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\Http\Middleware\RedirectIfAuthenticated->handle(Object(Illuminate\Http\Request), Object(Closure))
#38 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#42 /var/www/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#44 /var/www/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#45 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#46 /var/www/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#47 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#48 /var/www/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#50 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#51 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#52 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#53 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#54 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#55 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#56 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#57 /var/www/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#58 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#59 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#60 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#61 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#62 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#63 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#64 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#65 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#66 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#67 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#68 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#69 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#70 /var/www/public/index.php(55): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#71 {main}

Next LdapRecord\LdapRecordException: The given data was invalid. in /var/www/vendor/directorytree/ldaprecord/src/LdapRecordException.php:26
Stack trace:
#0 /var/www/vendor/directorytree/ldaprecord/src/Connection.php(318): LdapRecord\LdapRecordException::withDetailedError(Object(Illuminate\Validation\ValidationException), Object(LdapRecord\DetailedError))
#1 /var/www/vendor/directorytree/ldaprecord/src/Connection.php(208): LdapRecord\Connection->runOperationCallback(Object(Closure))
#2 /var/www/vendor/directorytree/ldaprecord/src/Connection.php(265): LdapRecord\Connection->connect()
#3 /var/www/vendor/directorytree/ldaprecord/src/Query/Builder.php(528): LdapRecord\Connection->run(Object(Closure))
#4 /var/www/vendor/directorytree/ldaprecord/src/Query/Builder.php(397): LdapRecord\Query\Builder->run('(&(objectclass=...')
#5 /var/www/vendor/directorytree/ldaprecord/src/Query/Builder.php(498): LdapRecord\Query\Builder->LdapRecord\Query\{closure}()
#6 /var/www/vendor/directorytree/ldaprecord/src/Query/Builder.php(400): LdapRecord\Query\Builder->getCachedResponse('(&(objectclass=...', Object(Closure))
#7 /var/www/vendor/directorytree/ldaprecord/src/Query/Builder.php(223): LdapRecord\Query\Builder->query('(&(objectclass=...')
#8 /var/www/vendor/directorytree/ldaprecord/src/Query/Builder.php(245): LdapRecord\Query\Builder->LdapRecord\Query\{closure}()
#9 /var/www/vendor/directorytree/ldaprecord/src/Query/Builder.php(224): LdapRecord\Query\Builder->onceWithColumns(Array, Object(Closure))
#10 /var/www/vendor/directorytree/ldaprecord/src/Query/Builder.php(691): LdapRecord\Query\Builder->get(Array)
#11 /var/www/vendor/directorytree/ldaprecord-laravel/src/LdapUserRepository.php(100): LdapRecord\Query\Builder->first()
#12 /var/www/vendor/directorytree/ldaprecord-laravel/src/Auth/UserProvider.php(46): LdapRecord\Laravel\LdapUserRepository->findByCredentials(Array)
#13 [internal function]: LdapRecord\Laravel\Auth\UserProvider->LdapRecord\Laravel\Auth\{closure}(Array)
#14 /var/www/vendor/directorytree/ldaprecord-laravel/src/Auth/UserProvider.php(62): call_user_func(Object(Closure), Array)
#15 /var/www/vendor/directorytree/ldaprecord-laravel/src/Auth/DatabaseUserProvider.php(142): LdapRecord\Laravel\Auth\UserProvider->fetchLdapUserByCredentials(Array)
#16 /var/www/vendor/laravel/framework/src/Illuminate/Auth/SessionGuard.php(357): LdapRecord\Laravel\Auth\DatabaseUserProvider->retrieveByCredentials(Array)
#17 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Auth/AuthenticatesUsers.php(82): Illuminate\Auth\SessionGuard->attempt(Array, false)
#18 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Auth/AuthenticatesUsers.php(45): App\Http\Controllers\Auth\LoginController->attemptLogin(Object(Illuminate\Http\Request))
#19 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\Http\Controllers\Auth\LoginController->login(Object(Illuminate\Http\Request))
#20 /var/www/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('login', Array)
#21 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\Auth\LoginController), 'login')
#22 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\Routing\Route->runController()
#23 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\Routing\Route->run()
#24 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#25 /var/www/app/Http/Middleware/RedirectIfAuthenticated.php(24): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\Http\Middleware\RedirectIfAuthenticated->handle(Object(Illuminate\Http\Request), Object(Closure))
#27 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 /var/www/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 /var/www/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /var/www/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /var/www/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#41 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#42 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#43 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#44 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#45 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#46 /var/www/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#47 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#48 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#50 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#51 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#52 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#53 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#54 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#55 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#56 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#57 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#58 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#59 /var/www/public/index.php(55): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#60 {main}  

[2021-01-21 12:12:14] local.INFO: Illuminate\Validation\ValidationException: The given data was invalid. in /var/www/vendor/laravel/framework/src/Illuminate/Validation/ValidationException.php:71
Stack trace:
#0 /var/www/vendor/directorytree/ldaprecord-laravel/src/Auth/ListensForLdapBindFailure.php(118): Illuminate\Validation\ValidationException::withMessages(Array)
#1 /var/www/vendor/directorytree/ldaprecord-laravel/src/Auth/ListensForLdapBindFailure.php(91): App\Http\Controllers\Auth\LoginController->throwLoginValidationException('Can't contact L...')
#2 /var/www/vendor/directorytree/ldaprecord-laravel/src/Auth/ListensForLdapBindFailure.php(62): App\Http\Controllers\Auth\LoginController->handleLdapBindError('Can't contact L...')
#3 /var/www/vendor/directorytree/ldaprecord-laravel/src/Auth/ListensForLdapBindFailure.php(44): App\Http\Controllers\Auth\LoginController->ldapBindFailed('Can't contact L...', NULL)
#4 /var/www/vendor/directorytree/ldaprecord/src/Events/Dispatcher.php(269): App\Http\Controllers\Auth\LoginController->LdapRecord\Laravel\Auth\{closure}(Object(LdapRecord\Auth\Events\Failed))
#5 /var/www/vendor/directorytree/ldaprecord/src/Events/Dispatcher.php(112): LdapRecord\Events\Dispatcher->LdapRecord\Events\{closure}('LdapRecord\\Auth...', Array)
#6 /var/www/vendor/directorytree/ldaprecord/src/Events/Dispatcher.php(93): LdapRecord\Events\Dispatcher->dispatch('LdapRecord\\Auth...', Array, false)
#7 /var/www/vendor/directorytree/ldaprecord/src/Auth/Guard.php(202): LdapRecord\Events\Dispatcher->fire(Object(LdapRecord\Auth\Events\Failed))
#8 /var/www/vendor/directorytree/ldaprecord/src/Auth/Guard.php(118): LdapRecord\Auth\Guard->fireFailedEvent('@@@@@@@@\#######', 'password')
#9 /var/www/vendor/directorytree/ldaprecord/src/Auth/Guard.php(135): LdapRecord\Auth\Guard->bind('@@@@@@@@\#######', 'password')
#10 /var/www/vendor/directorytree/ldaprecord/src/Connection.php(203): LdapRecord\Auth\Guard->bindAsConfiguredUser()
#11 /var/www/vendor/directorytree/ldaprecord/src/Connection.php(311): LdapRecord\Connection->LdapRecord\{closure}(Object(LdapRecord\Ldap))
#12 /var/www/vendor/directorytree/ldaprecord/src/Connection.php(208): LdapRecord\Connection->runOperationCallback(Object(Closure))
#13 /var/www/vendor/directorytree/ldaprecord/src/Connection.php(265): LdapRecord\Connection->connect()
#14 /var/www/vendor/directorytree/ldaprecord/src/Query/Builder.php(528): LdapRecord\Connection->run(Object(Closure))
#15 /var/www/vendor/directorytree/ldaprecord/src/Query/Builder.php(397): LdapRecord\Query\Builder->run('(&(objectclass=...')
#16 /var/www/vendor/directorytree/ldaprecord/src/Query/Builder.php(498): LdapRecord\Query\Builder->LdapRecord\Query\{closure}()
#17 /var/www/vendor/directorytree/ldaprecord/src/Query/Builder.php(400): LdapRecord\Query\Builder->getCachedResponse('(&(objectclass=...', Object(Closure))
#18 /var/www/vendor/directorytree/ldaprecord/src/Query/Builder.php(223): LdapRecord\Query\Builder->query('(&(objectclass=...')
#19 /var/www/vendor/directorytree/ldaprecord/src/Query/Builder.php(245): LdapRecord\Query\Builder->LdapRecord\Query\{closure}()
#20 /var/www/vendor/directorytree/ldaprecord/src/Query/Builder.php(224): LdapRecord\Query\Builder->onceWithColumns(Array, Object(Closure))
#21 /var/www/vendor/directorytree/ldaprecord/src/Query/Builder.php(691): LdapRecord\Query\Builder->get(Array)
#22 /var/www/vendor/directorytree/ldaprecord-laravel/src/LdapUserRepository.php(100): LdapRecord\Query\Builder->first()
#23 /var/www/vendor/directorytree/ldaprecord-laravel/src/Auth/UserProvider.php(46): LdapRecord\Laravel\LdapUserRepository->findByCredentials(Array)
#24 [internal function]: LdapRecord\Laravel\Auth\UserProvider->LdapRecord\Laravel\Auth\{closure}(Array)
#25 /var/www/vendor/directorytree/ldaprecord-laravel/src/Auth/UserProvider.php(62): call_user_func(Object(Closure), Array)
#26 /var/www/vendor/directorytree/ldaprecord-laravel/src/Auth/DatabaseUserProvider.php(142): LdapRecord\Laravel\Auth\UserProvider->fetchLdapUserByCredentials(Array)
#27 /var/www/vendor/laravel/framework/src/Illuminate/Auth/SessionGuard.php(357): LdapRecord\Laravel\Auth\DatabaseUserProvider->retrieveByCredentials(Array)
#28 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Auth/AuthenticatesUsers.php(82): Illuminate\Auth\SessionGuard->attempt(Array, false)
#29 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Auth/AuthenticatesUsers.php(45): App\Http\Controllers\Auth\LoginController->attemptLogin(Object(Illuminate\Http\Request))
#30 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\Http\Controllers\Auth\LoginController->login(Object(Illuminate\Http\Request))
#31 /var/www/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('login', Array)
#32 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\Auth\LoginController), 'login')
#33 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\Routing\Route->runController()
#34 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\Routing\Route->run()
#35 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#36 /var/www/app/Http/Middleware/RedirectIfAuthenticated.php(24): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\Http\Middleware\RedirectIfAuthenticated->handle(Object(Illuminate\Http\Request), Object(Closure))
#38 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#42 /var/www/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#44 /var/www/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#45 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#46 /var/www/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#47 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#48 /var/www/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#50 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#51 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#52 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#53 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#54 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#55 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#56 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#57 /var/www/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#58 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#59 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#60 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#61 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#62 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#63 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#64 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#65 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#66 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#67 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#68 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#69 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#70 /var/www/public/index.php(55): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#71 {main}

Next LdapRecord\LdapRecordException: The given data was invalid. in /var/www/vendor/directorytree/ldaprecord/src/LdapRecordException.php:26
Stack trace:
#0 /var/www/vendor/directorytree/ldaprecord/src/Connection.php(318): LdapRecord\LdapRecordException::withDetailedError(Object(Illuminate\Validation\ValidationException), Object(LdapRecord\DetailedError))
#1 /var/www/vendor/directorytree/ldaprecord/src/Connection.php(208): LdapRecord\Connection->runOperationCallback(Object(Closure))
#2 /var/www/vendor/directorytree/ldaprecord/src/Connection.php(265): LdapRecord\Connection->connect()
#3 /var/www/vendor/directorytree/ldaprecord/src/Query/Builder.php(528): LdapRecord\Connection->run(Object(Closure))
#4 /var/www/vendor/directorytree/ldaprecord/src/Query/Builder.php(397): LdapRecord\Query\Builder->run('(&(objectclass=...')
#5 /var/www/vendor/directorytree/ldaprecord/src/Query/Builder.php(498): LdapRecord\Query\Builder->LdapRecord\Query\{closure}()
#6 /var/www/vendor/directorytree/ldaprecord/src/Query/Builder.php(400): LdapRecord\Query\Builder->getCachedResponse('(&(objectclass=...', Object(Closure))
#7 /var/www/vendor/directorytree/ldaprecord/src/Query/Builder.php(223): LdapRecord\Query\Builder->query('(&(objectclass=...')
#8 /var/www/vendor/directorytree/ldaprecord/src/Query/Builder.php(245): LdapRecord\Query\Builder->LdapRecord\Query\{closure}()
#9 /var/www/vendor/directorytree/ldaprecord/src/Query/Builder.php(224): LdapRecord\Query\Builder->onceWithColumns(Array, Object(Closure))
#10 /var/www/vendor/directorytree/ldaprecord/src/Query/Builder.php(691): LdapRecord\Query\Builder->get(Array)
#11 /var/www/vendor/directorytree/ldaprecord-laravel/src/LdapUserRepository.php(100): LdapRecord\Query\Builder->first()
#12 /var/www/vendor/directorytree/ldaprecord-laravel/src/Auth/UserProvider.php(46): LdapRecord\Laravel\LdapUserRepository->findByCredentials(Array)
#13 [internal function]: LdapRecord\Laravel\Auth\UserProvider->LdapRecord\Laravel\Auth\{closure}(Array)
#14 /var/www/vendor/directorytree/ldaprecord-laravel/src/Auth/UserProvider.php(62): call_user_func(Object(Closure), Array)
#15 /var/www/vendor/directorytree/ldaprecord-laravel/src/Auth/DatabaseUserProvider.php(142): LdapRecord\Laravel\Auth\UserProvider->fetchLdapUserByCredentials(Array)
#16 /var/www/vendor/laravel/framework/src/Illuminate/Auth/SessionGuard.php(357): LdapRecord\Laravel\Auth\DatabaseUserProvider->retrieveByCredentials(Array)
#17 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Auth/AuthenticatesUsers.php(82): Illuminate\Auth\SessionGuard->attempt(Array, false)
#18 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Auth/AuthenticatesUsers.php(45): App\Http\Controllers\Auth\LoginController->attemptLogin(Object(Illuminate\Http\Request))
#19 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\Http\Controllers\Auth\LoginController->login(Object(Illuminate\Http\Request))
#20 /var/www/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('login', Array)
#21 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\Auth\LoginController), 'login')
#22 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\Routing\Route->runController()
#23 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\Routing\Route->run()
#24 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#25 /var/www/app/Http/Middleware/RedirectIfAuthenticated.php(24): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\Http\Middleware\RedirectIfAuthenticated->handle(Object(Illuminate\Http\Request), Object(Closure))
#27 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 /var/www/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 /var/www/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /var/www/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /var/www/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#41 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#42 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#43 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#44 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#45 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#46 /var/www/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#47 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#48 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#50 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#51 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#52 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#53 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#54 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#55 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#56 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#57 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#58 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#59 /var/www/public/index.php(55): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#60 {main}  
```
```

**Comment by LunaTakaishi** [comment]
Yes, this is bizarre. Because  It works fine when I put a valid host in the first of the array.

I use "DATABASE AUTH". Maybe I fixed it normally.

- LoginController added
![image](https://user-images.githubusercontent.com/28255411/105277849-99276180-5be7-11eb-8df1-397e84ca8c42.png)

- config\ldap.php
![image](https://user-images.githubusercontent.com/28255411/105277927-cb38c380-5be7-11eb-98ab-c8841fcbb1fc.png)

- config\auth.php
![image](https://user-images.githubusercontent.com/28255411/105278110-2c609700-5be8-11eb-9740-4eb677b7a52f.png)
![image](https://user-images.githubusercontent.com/28255411/105277982-e9062880-5be7-11eb-9d0e-b720bc737a83.png)


If you don't have enough information, please let me know.

**Comment by stevebauman** [comment]
Hi @LunaTakaishi,

Thanks for posting all of that detail -- I'm now able to reproduce this using LdapRecord-Laravel and attempting to log users in.

This is due to the `LdapUserAuthenticator` calling the `auth()->attempt()` method explicitly, which isn't set up to failover to another host... I'll have to see if there's an implementation I can use to resolve this. 👍

**Comment by LunaTakaishi** [comment]
Hi @stevebauman,
Thanks for considering the fix for me.
I understood that "AAA" was the trigger.We look forward to the release of the fix!

**Comment by LunaTakaishi** [comment]
Hi @stevebauman,
Is the fix going well? Is there anything I can do?
Thank you for fixing it for me.

**Comment by stevebauman** [comment]
Hi @LunaTakaishi!

> Is the fix going well?

Yup! It's already fixed -- I'll be making a release tomorrow morning, as I've created a brand new testing framework built into LdapRecord to help test this sort of functionality 🎉.

I'll post here as soon as I create the release so you're up to date and aware of its arrival 👍.

**Comment by stevebauman** [comment]
Hi @LunaTakaishi,

A new release has just been pushed ([v2.1.0](https://github.com/DirectoryTree/LdapRecord/releases/tag/v2.1.0)).

However, while this has resolved the issue in the LdapRecord code repository, I have to make a small update to the LdapRecord-Laravel repo as well so it utilizes the fallback properly.

I'll have this new version of LdapRecord-Laravel out tomorrow and I'll post back here once done 🎉

**Comment by LunaTakaishi** [comment]
Hi @stevebauman ,

Thank you very much for the new release.🎉
I'll wait for a fix to Laravel. I'm looking forward to tomorrow.

Thank you for always reading my English.😂

**Comment by LunaTakaishi** [comment]
Hi @stevebauman,
I am waiting for an update of LdapRecord-Laravel repo.
Is it still going to take time? I would appreciate it if you could get back to me at your earliest convenience.

**Comment by stevebauman** [comment]
Hi @LunaTakaishi,

I’m still working on the update to LdapRecord-Laravel. Life has gotten in the way a bit for me to complete the update when I was supposed to have it finished.

Have you tried running composer update? Are you using Jetstream or Laravel UI?

**Comment by LunaTakaishi** [comment]
Hi @stevebauman, 

I did composer update, but ldaprecord doesn't upgrade.

- composer  
`"directorytree / ldaprecord-laravel": "^ 2.0",`

- result
  `--Installing directorytree / ldaprecord (v2.0.4): Loading from cache`
  `--Installing directorytree / ldaprecord-laravel (v2.0.1): Loading from cache`

I'm not using Jetstream or Laravel UI.

**Comment by stevebauman** [comment]
That’s strange — can you post your whole `composer.json` file?

**Comment by LunaTakaishi** [comment]
Until now, I wrote as follows.
         `"directorytree / ldaprecord-laravel": "^ 2.0",`

However, I realized that I should write it like this.
```
 "directorytree / ldaprecord": "^ 2.1",
         "directorytree / ldaprecord-laravel": "^ 2.0",
```

I have successfully updated ldaprecord!

**Comment by stevebauman** [comment]
Strange! It should have updated the core LdapRecord repository without specifying it manually... I’ll check this out.

Can you try authentication again with the latest? If you’re not using Jetstream or UI, you should be good to go!

**Comment by LunaTakaishi** [comment]
I tried authentication again, but it didn't work...
Something may be wrong.

**Comment by LunaTakaishi** [comment]
sorry.
After composer clear-cache, ldaprecord v2.1.1 was installed with only ldaprecord-laravel description!

**Comment by stevebauman** [comment]
No problem @LunaTakaishi!

I performed a test on my own LDAP server using Laravel Jetstream and failover is actually working perfectly 😄 

Can you give it a shot and let me know your results?

In my testing, I can add as many invalid hosts as I want, but it will continuously keep trying the next host in line until ultimately failing if the last host fails:

```
[2021-02-05 02:35:23] local.INFO: LDAP (ldap://10.211.55.1:389) - Operation: Binding - Username: cn=admin,dc=local,dc=com  
[2021-02-05 02:35:26] local.WARNING: LDAP (ldap://10.211.55.1:389) - Operation: Failed - Username: cn=admin,dc=local,dc=com - Reason: Can't contact LDAP server  
[2021-02-05 02:35:26] local.INFO: LDAP (ldap://10.211.55.2:389) - Operation: Binding - Username: cn=admin,dc=local,dc=com  
[2021-02-05 02:35:26] local.WARNING: LDAP (ldap://10.211.55.2:389) - Operation: Failed - Username: cn=admin,dc=local,dc=com - Reason: Can't contact LDAP server  
[2021-02-05 02:35:26] local.INFO: LDAP (ldap://10.211.55.3:389) - Operation: Binding - Username: cn=admin,dc=local,dc=com  
[2021-02-05 02:35:26] local.INFO: LDAP (ldap://10.211.55.3:389) - Operation: Bound - Username: cn=admin,dc=local,dc=com  
[2021-02-05 02:35:26] local.INFO: LDAP (ldap://10.211.55.3:389) - Operation: Search - Base DN: ...
[2021-02-05 02:35:26] local.INFO: User [admin] has been successfully discovered for authentication.  
[2021-02-05 02:35:26] local.INFO: Object with name [admin] is being synchronized.  
[2021-02-05 02:35:26] local.INFO: Object with name [admin] has been successfully synchronized.  
[2021-02-05 02:35:26] local.INFO: User [admin] is authenticating.  
```

Notice the subsequent retries in the IP addresses specified in the above logs.

- 10.211.55.1 (fails)
- 10.211.55.2 (fails)
- 10.211.55.3 (works)

**Comment by LunaTakaishi** [comment]
Hi @stevebauman,

I tried authentication again, but it didn't work...
Only this is spit out to the Log file.
`[2021-02-05 11:42:46] local.INFO: LDAP (ldap://172.20.3.8:389) - Operation: Binding - Username: XXXXXXXX  `

 I modified it.

- .env
```
LDAP_HOST=172.20.3.8,172.20.3.9
```

- config/ldap.php
```
'connections' => [
        'default' => [
            'hosts' => array_map('trim', explode(',', env('LDAP_HOST', '127.0.0.1'))), // I modified it here
```

**Comment by stevebauman** [comment]
Can you post your `LoginController` and your `composer.json` file? Also -- can you try updating your `composer.json` file to update to the latest LdapRecord-Laravel version by using `dev-master`? For example:

```json
"directorytree/ldaprecord-laravel": "dev-master",
```

Then, run `composer update` -- and attempt authenticating again after the latest `dev-master` build has been downloaded.

I have a feeling you may be using Laravel UI -- judging by your exception message posted in the chat above:

```
#17 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Auth/AuthenticatesUsers.php(82): Illuminate\Auth\SessionGuard->attempt(Array, false)
#18 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Auth/AuthenticatesUsers.php(45): App\Http\Controllers\Auth\LoginController->attemptLogin(Object(Illuminate\Http\Request))
#19 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\Http\Controllers\Auth\LoginController->login(Object(Illuminate\Http\Request))
```

**Comment by LunaTakaishi** [comment]
Hi, @stevebauman, I tried the above and it worked!
Wonderful 🎉. thank you very much!

Maybe I'm not using laravel-ui. How can I check if it is being used?
Just in case, put composer.js and LoginController.

```
{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=7.4.0",
        "almasaeed2010/adminlte": "~2.4",
        "directorytree/ldaprecord-laravel": "dev-master",
        "fideloper/proxy": "^4.0",
        "fortawesome/font-awesome": "5.*",
        "illuminate/support": "^6.0",
        "laravel/framework": "^6.0",
        "laravel/helpers": "^1.4",
        "laravel/tinker": "^2.0"
    },
    "require-dev": {
        "filp/whoops": "~2.0",
        "fakerphp/faker": "~1.9",
        "mockery/mockery": "~1.0",
        "phpunit/phpunit": "^7.0",
        "squizlabs/php_codesniffer": "3.*",
        "symfony/thanks": "^1.0"
    },
    "autoload": {
        "classmap": [
            "database/seeds",
            "database/factories"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "extra": {
        "laravel": {
            "dont-discover": [
            ]
        }
    },
    "scripts": {
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate"
        ],
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover"
        ],
        "post-install-cmd": [
            "@php artisan vendor:publish --tag=public-vendor --force"
        ],
        "post-update-cmd": [
            "@php artisan vendor:publish --tag=public-vendor --force"
        ]
    },
    "config": {
        "preferred-install": "dist",
        "sort-packages": true,
        "optimize-autoloader": true
    },
    "repositories": [
        {
             "type": "package",
             "package": {
                 "name": "fortawesome/font-awesome",
                 "version": "5.0.6",
                 "source": {
                     "url": "https://github.com/FortAwesome/Font-Awesome.git",
                     "type": "git",
                     "reference": "5.0.6"
                 }
             }
         }
     ]
}
```

```
<?php

namespace App\Http\Controllers\Auth;

use App\Http\Controllers\Controller;
use Illuminate\Foundation\Auth\AuthenticatesUsers;
use Illuminate\Http\Request;
use LdapRecord\Laravel\Auth\ListensForLdapBindFailure;

class LoginController extends Controller
{
    use AuthenticatesUsers {
        //ログアウト後の遷移先変更
        logout as performLogout;
    }
    use ListensForLdapBindFailure;
    /*
    |--------------------------------------------------------------------------
    | Login Controller
    |--------------------------------------------------------------------------
    |
    | This controller handles authenticating users for the application and
    | redirecting them to your home screen. The controller uses a trait
    | to conveniently provide its functionality to your applications.
    |
    */
    public function username()
    {
        return 'login_id';
    }

    /**
     * ログイン時のバリデーションカスタマイズ
     *
     * @param Request $request
     * @return void
     */
    protected function validateLogin(Request $request)
    {
        $this->validate(
            $request,
            [
                $this->username() => 'required',
                'password' => 'required',
            ],
            [],
            [   $this->username() => 'ユーザ名'
            ]
        );
    }

    public function logout(Request $request)
    {
        $this->performLogout($request);
        return redirect()->route('login');
    }

    /**
     * Where to redirect users after login.
     *
     * @var string
     */
    protected $redirectTo = 'home';

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('guest')->except('logout');
    }

    protected function credentials(Request $request)
    {
        return [
            'samaccountname' => $request->login_id,
            'password' => $request->password,
            'fallback' => [
                'login_id' => $request->login_id,
                'password' => $request->password,
            ],
        ];
    }
}
```

**Comment by stevebauman** [comment]
Awesome @LunaTakaishi! I'm so glad you're up and running. I should have a new tested release out today of LdapRecord-Laravel.

Also -- my apologies, you're using Laravel 6, which included the default authentication scaffolding, which was removed in Laravel 7 and extracted to the Laravel UI package. Thanks for pasting all that information for me to determine that.

Once the new release is out, I will close this issue 👍 .

**Comment by stevebauman** [comment]
LdapRecord-Laravel [v2.1.0](https://github.com/DirectoryTree/LdapRecord-Laravel/releases/tag/v2.1.0) has just been released with all these fixes 🎉 

Thanks for your help debugging this @LunaTakaishi! ❤️
